name: test-reusable-build
run-name: Build Docker Image
on:
  workflow_call:
    outputs:
      docker_ps:
        description: "The output of docker ps command"
        value: ${{ jobs.delpoy-app.outputs.docker_ps }}
jobs:
  delpoy-app:
    outputs:
      docker_ps: ${{ steps.docker_ps.outputs.out }}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout workflows repo
        uses: actions/checkout@v4
        with:
          repository: compliance-framework/workflows
          ref: main
          fetch-depth: 1
          show-progress: false
      - name: Test Directory
        run: 
          pwd
          ls -la
          ls -la ./assessment-runtime
          echo "${{ secrets.GH_DEPL_KEY_CONF_SVC }}"
      - name: Checkout configuration-service repo
        uses: actions/checkout@v4
        with:
          repository: compliance-framework/configuration-service
          ref: main
          ssh-key: ${{ secrets.GH_DEPL_KEY_CONF_SVC }}
          fetch-depth: 1
          show-progress: false
      - name: Checkout assessment-runtime repo
        uses: actions/checkout@v4
        with:
          repository: compliance-framework/assessment-runtime
          ref: main
          fetch-depth: 1
          show-progress: false
      - name: Run the Docker Compose
        run: 
          pwd
          ls -la
          docker compose -f workflows/docker-compose.yml up
      - name: Check running containers
        id: docker_ps
        run: echo "out=\"$(docker ps -a | xargs)\"" >> "$GITHUB_OUTPUT"

