name: test-reusable-build
run-name: Build Docker Image
on:
  workflow_call:
    outputs:
      docker_ps:
        description: "The output of docker ps command"
        value: ${{ jobs.assessment-runtime.outputs.docker_ps }}
jobs:
  assessment-runtime:
    outputs:
      docker_ps: ${{ steps.docker_ps.outputs.out }}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout assessment-runtime repo
        uses: actions/checkout@v4
        with:
          repository: compliance-framework/assessment-runtime
          path: assessment-runtime
          ref: main
          fetch-depth: 1
          show-progress: false
      - name: List Directories
        run:
          ls -la          
      - name: Run the Docker Compose
        working-directory: ./test
        run: docker-compose -f docker-compose.yml up -d
      - name: Check running containers
        id: docker_ps
        run: echo "out=\"$(docker ps -a | xargs)\"" >> "$GITHUB_OUTPUT"

