name: Build and Upload Plugin Artifacts

on:
  workflow_call:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install gooci cli
        run: go install github.com/compliance-framework/gooci@latest
      - name: Authenticate gooci cli
        run: gooci login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
      - name: gooci Upload Version
        run: | # strip 'v' from tag
          TAG=${GITHUB_REF_NAME#v}
          gooci upload dist/ ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${TAG}
      - name: gooci Upload Latest
        if: ${{ !github.event.release.prerelease }}
        run: gooci upload dist/ ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
